apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: example-replicaset
  labels: 
    app: my-app
spec:
  replicas: 3
  selector: 
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - image: nginx
          name: my-nginx